### ISSUE TITLE
`Ada.Text_IO.` missing in a template

### ISSUE THREAD

**Issue by zertovitch** [Ada-France/aflex#5]
On testing aflex_1.6.0_b3c21d99 for P2Ada, I get:
pascal_io.adb:108:7: error: "Put_Line" is not visible

...which is solved by adding a heading "Ada.Text_IO" at line 288 of template_manager-templates.ads
   L_165 : aliased constant String := "      Put_Line (""Input line """;

...or better (I guess) at line 125 of templates/body-io.adb

**Comment by stcarrez** [comment]
Thanks! I've tried to cleanup the generated code to make it more Ada 95 friendly but I was not able to verify completely the aflex -E option.

Yes, the fix must be made in templates/body-io.adb
