### ISSUE TITLE
Maybe support larger integer types for yylineno

### ISSUE THREAD

**Issue by krcurtis** [Ada-France/aflex#6]
It would be helpful to be able to specify different integer types for yylineno. I thought I'd try an Ada-based solution and was trying to use aflex and ayacc to verify a 270GB FASTA file (it is supposed to have a very regular structure).  Unfortunately I got an exception:
```
raised CONSTRAINT_ERROR : scanfasta_lexer.adb:221 overflow check failed
```

For now, I'm manually forcing yylineno and yy_last_yylineno to be a custom type in the _dfa.ads file. It would be nice to be able to specify that in a different file that would not be overwritten during the build process.

Thanks!

**Comment by stcarrez** [comment]
Fixed in 1.7 version.
You can declare in the lexer file something like:

```
%option yylinenotype=Line_Number
%yydfa {
   subtype Line_Number is Long_Long_Integer;
}
```

The `%yydfa` code block is injected in the `_dfa.ads` package declaration before the declaration of the `yylineno` variables.
